### ISSUE TITLE
KeyError 'items'

### ISSUE THREAD

**Issue by Ehco1996** [rrwen/search_google#1]
Hi buddy , you project is  amazing !!!
but when i try to deploy on my own system,
some bad thing happened
please help me to find out what step is wrong

> i  have already set the google search cx and api key

this is log:

```
Traceback (most recent call last):
  File "/usr/local/var/pyenv/versions/venv-3.6.1/bin/search_google", line 11, in <module>
    load_entry_point('search-google==1.2.0', 'console_scripts', 'search_google')()
  File "/usr/local/var/pyenv/versions/3.6.1/envs/venv-3.6.1/lib/python3.6/site-packages/search_google/cli.py", line 155, in run
    results.preview(n=int(optionargs['preview']))
  File "/usr/local/var/pyenv/versions/3.6.1/envs/venv-3.6.1/lib/python3.6/site-packages/search_google/api.py", line 153, in preview
    items = self.metadata[k]
KeyError: 'items'
```

**Comment by rrwen** [comment]
Hi @Ehco1996

Thank you for the issue submission. 
  
Could you provide me with the *command line call* or *python call* that raised this *error*?  
  
Please do not include your google search cx and api key credentials.

**Comment by Ehco1996** [comment]
@rrwen 

after i reset the cx id and api key ,
those problem gone
thank you again !!!

**Comment by jennymansour96** [comment]
Hello @Ehco1996. I have exactly the same problem, how did you reset cx id and api key? I tried to define them again, but it is still not working...
Thank you very much!!

**Comment by rrwen** [comment]
@jennymansour96

You can reset the cx id and api key by deleting the old ones and generating new ones in the managment console.

Please note that the Google CSE API has rate limits.

**Comment by Erroneous-User** [comment]
I'm too facing same problem.
but how exactly I reset cx id and api key.
i don't have any idea about them

**Comment by rrwen** [comment]
@Adarshnerd 

Please follow the documentation to create a cx id and an api key:

https://rrwen.github.io/search_google/#setup

To reset them, delete and recreate
