### ISSUE TITLE
num cannot be greater than 10

### ISSUE THREAD

**Issue by jradis** [rrwen/search_google#2]
At first I couldn't figure out why it wouldn't let me get more records than ten records : 

HttpError: <HttpError 400 when requesting https://www.googleapis.com/customsearch/v1?searchType=i
ne+screenshot&num=99&fileType=png&cx=[MYCXID]&key=[MYKEY]=json returned "Invalid Value"

I found that it is because of Google's API limit:

num | unsigned integer | Number of search results to return.Valid values are integers between 1 and 10, inclusive.
[https://developers.google.com/custom-search/json-api/v1/reference/cse/list](https://developers.google.com/custom-search/json-api/v1/reference/cse/list)

Is there any workaround for this that you would suggest?

**Comment by rrwen** [comment]
Hi @jradis,

Please see: https://stackoverflow.com/questions/16925762/getting-more-than-10-results-by-google-custom-search-api-v1-in-java

You may edit the `start` query parameter, and make multiple calls in batches of 10:

```
search_google cats --start=0
search_google cats --start=11
```

You may also loop this in Python:

```python
import search_google.api

# Define buildargs for cse api
buildargs = {
  'serviceName': 'customsearch',
  'version': 'v1',
  'developerKey': 'your_api_key'
}

# Define cseargs for search
cseargs = {
  'q': 'keyword query',
  'cx': 'your_cse_id'
}

# Create a results object
results = []
for (start in [0, 11]) {
  cseargs['start'] = start
  results.append(search_google.api.results(buildargs, cseargs)
}

# Preview results for start=0
results[0].preview()

# Preview results for start=11
results[1].preview()
```
