### ISSUE TITLE
Wants to extract my whats up chat backup communication present on google drive 

### ISSUE THREAD

**Issue by Pavan7678** [rrwen/search_google#3]
Steps taken by me as present on this video of Youtube.

https://www.youtube.com/watch?v=7ZMEgcpD9vc

Downloaded python 3.7
WhatsApp-GD-Extractor-master file.
Whats up Viewer
Extracted the file WhatsApp-GD-Extractor-master. Made changes in it's setting file accordingly Put my user name and password in it.

By using command prompt, I do run .py file by using python setup. And then below error is coming.

Traceback (most recent call last):
     File "WhatsAppGDExtract.py",         line 218, in <module>

main()
     File "WhatsAppGDExtract.py", line 201, in main

     runMain('list', 'all', 0)

     File "WhatsAppGDExtract.py", line 149, in runMain

     *emphasized text*bearer = getGoogleDriveToken(getGoogleAccountTokenFromAuth())
Resolution https://github.com/rrwen/search_google/issues/1

@Adarshnerd rrwen commented on Jul 16

Please follow the documentation to create a cx id and an api key:

https://rrwen.github.io/search_google/#setup

Proceed to following procedure:-

Google Custom Search Engine A Google Custom Search Engine (CSE) and a CSE ID can be setup with the following instructions:

Go to the CSE Control Panel
Click Add
Enter a website in the box under Sites to search such as “www.google.com” Click Create
Go back to the CSE Control Panel
Select your created search engine
Turn on Image search For Sites to search, select Search the entire web but emphasize included sites
Under Sites to search, click checkbox next to Site
Under Sites to search, click Delete
Under Details, click Search engine ID
Set cx by replacing “your_cse_id” with the Search engine ID
Completed up till this but don't understand line number 10. not clarify what to do ahead?

Please help now how to go ahead.

**Comment by rrwen** [comment]
Hi @Pavan7678 

Perhaps there has been a misunderstanding, but this package is meant to be used for extracting Google Search Engine results, and not for extracting a WhatsApp database from Google Drive.

However, I am happy to answer your reference to closed issue #1. If I understand you correctly, it seems that you wish to create a **Google Custom Search Engine (CSE)** and a **CSE ID**.

This can be achieved below:

**Step 10** on [the setup page](https://rrwen.github.io/search_google/#google-custom-search-engine) refers to deleting any sites that you put in your Google CSE as it will not be needed for the purpose of the package.

![searchgoogle_issue_02_01](https://user-images.githubusercontent.com/4625410/44302906-a77b4000-a300-11e8-9c5c-e5f83e9f658e.PNG)
